/** 이 데이터는 오늘 발표된 coivd19 확진자 현황 데이터 입니다.
confirmed는 코로나 발생일로부터 현재까지의 누적 확진자를 의미하고,
confirmed_prev는 어제까지의 확진자를 의미합니다.
이를 토대로 하여 각 지역별 오늘 발생한 확진자 수를 출력하시오. */
{
    "state"= [
        {
            "region": "서울",
            "confirmed": 120240,
            "death": 796,
            "released": 107550,
            "vaccinatedOnce": 119118,
            "vaccinatedFully": 1283,
            "active": 11894,
            "confirmed_prev": 119594,
            "released_prev": 107550,
            "death_prev": 796,
            "active_prev": 11248,
            "vaccinatedOnce_prev": 119118,
            "vaccinatedFully_prev": 1283
        },
        {
            "region": "부산",
            "confirmed": 13966,
            "death": 161,
            "released": 13301,
            "vaccinatedOnce": 56813,
            "vaccinatedFully": 0,
            "active": 504,
            "confirmed_prev": 13911,
            "released_prev": 13301,
            "death_prev": 161,
            "active_prev": 449,
            "vaccinatedOnce_prev": 56813,
            "vaccinatedFully_prev": 0
        },
        {
            "region": "대구",
            "confirmed": 17199,
            "death": 261,
            "released": 16278,
            "vaccinatedOnce": 34085,
            "vaccinatedFully": 0,
            "active": 660,
            "confirmed_prev": 17142,
            "released_prev": 16278,
            "death_prev": 261,
            "active_prev": 603,
            "vaccinatedOnce_prev": 34085,
            "vaccinatedFully_prev": 0
        },
        {
            "region": "인천",
            "confirmed": 19500,
            "death": 108,
            "released": 17506,
            "vaccinatedOnce": 40018,
            "vaccinatedFully": 115,
            "active": 1886,
            "confirmed_prev": 19373,
            "released_prev": 17506,
            "death_prev": 108,
            "active_prev": 1759,
            "vaccinatedOnce_prev": 40018,
            "vaccinatedFully_prev": 115
        },
        {
            "region": "광주",
            "confirmed": 5376,
            "death": 29,
            "released": 5261,
            "vaccinatedOnce": 29080,
            "vaccinatedFully": 0,
            "active": 86,
            "confirmed_prev": 5371,
            "released_prev": 5261,
            "death_prev": 29,
            "active_prev": 81,
            "vaccinatedOnce_prev": 29080,
            "vaccinatedFully_prev": 0
        },
        {
            "region": "대전",
            "confirmed": 7541,
            "death": 54,
            "released": 7360,
            "vaccinatedOnce": 22439,
            "vaccinatedFully": 0,
            "active": 127,
            "confirmed_prev": 7532,
            "released_prev": 7360,
            "death_prev": 54,
            "active_prev": 118,
            "vaccinatedOnce_prev": 22439,
            "vaccinatedFully_prev": 0
        },
        {
            "region": "울산",
            "confirmed": 5433,
            "death": 56,
            "released": 5316,
            "vaccinatedOnce": 14240,
            "vaccinatedFully": 0,
            "active": 61,
            "confirmed_prev": 5421,
            "released_prev": 5316,
            "death_prev": 56,
            "active_prev": 49,
            "vaccinatedOnce_prev": 14240,
            "vaccinatedFully_prev": 0
        },
        {
            "region": "세종",
            "confirmed": 1367,
            "death": 2,
            "released": 1340,
            "vaccinatedOnce": 2127,
            "vaccinatedFully": 0,
            "active": 25,
            "confirmed_prev": 1365,
            "released_prev": 1340,
            "death_prev": 2,
            "active_prev": 23,
            "vaccinatedOnce_prev": 2127,
            "vaccinatedFully_prev": 0
        },
        {
            "region": "경기",
            "confirmed": 109027,
            "death": 931,
            "released": 99489,
            "vaccinatedOnce": 149225,
            "vaccinatedFully": 95,
            "active": 8607,
            "confirmed_prev": 108463,
            "released_prev": 99489,
            "death_prev": 931,
            "active_prev": 8043,
            "vaccinatedOnce_prev": 149225,
            "vaccinatedFully_prev": 95
        },
        {
            "region": "강원",
            "confirmed": 7212,
            "death": 67,
            "released": 6907,
            "vaccinatedOnce": 21669,
            "vaccinatedFully": 5,
            "active": 238,
            "confirmed_prev": 7199,
            "released_prev": 6907,
            "death_prev": 67,
            "active_prev": 225,
            "vaccinatedOnce_prev": 21669,
            "vaccinatedFully_prev": 5
        },
        {
            "region": "충북",
            "confirmed": 7921,
            "death": 83,
            "released": 7364,
            "vaccinatedOnce": 21027,
            "vaccinatedFully": 0,
            "active": 474,
            "confirmed_prev": 7900,
            "released_prev": 7364,
            "death_prev": 83,
            "active_prev": 453,
            "vaccinatedOnce_prev": 21027,
            "vaccinatedFully_prev": 0
        },
        {
            "region": "충남",
            "confirmed": 10647,
            "death": 59,
            "released": 9835,
            "vaccinatedOnce": 28586,
            "vaccinatedFully": 0,
            "active": 753,
            "confirmed_prev": 10600,
            "released_prev": 9835,
            "death_prev": 59,
            "active_prev": 706,
            "vaccinatedOnce_prev": 28586,
            "vaccinatedFully_prev": 0
        },
        {
            "region": "전북",
            "confirmed": 5213,
            "death": 66,
            "released": 4824,
            "vaccinatedOnce": 31304,
            "vaccinatedFully": 0,
            "active": 323,
            "confirmed_prev": 5187,
            "released_prev": 4824,
            "death_prev": 66,
            "active_prev": 297,
            "vaccinatedOnce_prev": 31304,
            "vaccinatedFully_prev": 0
        },
        {
            "region": "전남",
            "confirmed": 3561,
            "death": 22,
            "released": 3382,
            "vaccinatedOnce": 35514,
            "vaccinatedFully": 0,
            "active": 157,
            "confirmed_prev": 3543,
            "released_prev": 3382,
            "death_prev": 22,
            "active_prev": 139,
            "vaccinatedOnce_prev": 35514,
            "vaccinatedFully_prev": 0
        },
        {
            "region": "경북",
            "confirmed": 9736,
            "death": 95,
            "released": 9224,
            "vaccinatedOnce": 37623,
            "vaccinatedFully": 0,
            "active": 417,
            "confirmed_prev": 9709,
            "released_prev": 9224,
            "death_prev": 95,
            "active_prev": 390,
            "vaccinatedOnce_prev": 37623,
            "vaccinatedFully_prev": 0
        },
        {
            "region": "경남",
            "confirmed": 13058,
            "death": 41,
            "released": 12427,
            "vaccinatedOnce": 52280,
            "vaccinatedFully": 0,
            "active": 590,
            "confirmed_prev": 13008,
            "released_prev": 12427,
            "death_prev": 41,
            "active_prev": 540,
            "vaccinatedOnce_prev": 52280,
            "vaccinatedFully_prev": 0
        },
        {
            "region": "제주",
            "confirmed": 3102,
            "death": 2,
            "released": 3037,
            "vaccinatedOnce": 8464,
            "vaccinatedFully": 0,
            "active": 63,
            "confirmed_prev": 3100,
            "released_prev": 3037,
            "death_prev": 2,
            "active_prev": 61,
            "vaccinatedOnce_prev": 8464,
            "vaccinatedFully_prev": 0
        }
    ]
}
